name: CI/CD Pipeline - API Node

on:
    push:
        branches:
            - main

jobs:
    security-sast:
        name: SAST (Segurança)
        runs-on: ubuntu-latest
        steps:
            - name: checkout falhas e vulnerabilidades
              uses: ajinabraham/njsscan-action@master
              with:
                args: "."

    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: checkout do código
              uses: actions/checkout@v5

            - name: configurar o Node.js
              uses: actions/setup-node@v5
              with:
                node-version: "24"
                cache: "npm"

            - name: instalar dependencias
              run: npm install

            - name: compilar código
              run: npm run build

    lint-and-quality:
        name: Lint & Quality
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: checkout do código
              uses: actions/checkout@v5

            - name: configurar o Node.js
              uses: actions/setup-node@v5
              with:
                node-version: "24"
                cache: "npm"

            - name: instalar dependências
              run: npm install

            - name: executar linter (ESLint)
              run: npm run lint

    test:
        name: Test
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: checkout do código
              uses: actions/checkout@v5

            - name: configurar Node.js
              uses: actions/setup-node@v5
              with:
                node-version: "24"
                cache: "npm"

            - name: instalar depdendências
              run: npm install

            - name: executar testes unitarios (Jest)
              run: npm test

    docker:
      name: Build do Docker
      needs: [ lint-and-quality, test ]
      if: ${{ success() }}
      
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Source Code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Authenticate to Contaner Registry
          uses: docker/login-action@v3
          with: 
            username: ${{ secrets.DOCKER_API_LOGIN }}
            password: ${{ secrets.DOCKER_API_PASSWORD }}

        - name: Build and Push to Docker Hub
          uses: docker/build-push-action@v6
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: |
              ${{ secrets.DOCKER_API_LOGIN }}/desafio-fluxo-fap:1.0.${{ github.run_number }}
              ${{ secrets.DOCKER_API_LOGIN }}/desafio-fluxo-fap:latest
              ${{ secrets.DOCKER_API_LOGIN }}/desafio-fluxo-fap:${{ github.sha }}
            cache-from: type-gha
            cache-to: type=gha,mode=max

